@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "userName": "johndoe",
    "email": "johndoe@email.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "andregparada@email.com",
    "password": "123456"
}

###

// ??? receita com mesmo nome
# @name create_recipe
POST {{baseUrl}}/recipes
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Outra Receita",
    "description": "Descrição da receita",
    "instructions": "Instruções da receita",
    "prepTimeInMinutes": 30,
    "cookTimeInMinutes": 60,
    "servings": 4,
    "difficultyLevel": "easy",
    "tagsIds": [],
    "recipeIngredients": []
}

###

# @name get_recipe_by_slug
GET {{baseUrl}}/recipes/nova-receita
Content-Type: application/json
Authorization: Bearer {{authToken}}